version: 2.5.3.{build}

configuration: Release

platform: Any CPU

assembly_info:
  patch: true
  file: ./ChatExchange.Net/Properties/AssemblyInfo.cs
  assembly_version: '2.5.3'
  assembly_file_version: '{version}'
  assembly_informational_version: '2.5.3-beta'

install:
- git submodule update --init --recursive

before_build:
- nuget restore

build:
  project: ChatExchange.Net.sln
  parallel: true
  verbosity: minimal
  
deploy:
- provider: NuGet
  api_key:
    secure: vVmfmmg09BJVlqMuiWrSGPo0LXGlJ8HzWfysbHPpZonMQMOd82oiB+1ioKZQEsZH
  skip_symbols: true
  on:
    branch: master
