image: Visual Studio 2017
version: 6.0.{build}.0
configuration: Release
test: off # for now

before_build:
- dotnet restore

build:
  project: ChatExchange.Net.sln
  parallel: true
  verbosity: minimal

after_build:
- ps: msbuild ChatExchange.Net /t:pack /p:Configuration=Release

artifacts:
- path: ChatExchange.Net\bin\Release\netstandard1.6\ChatExchange.Net.dll
  name: ChatExchange.Net.dll
- path: ChatExchange.Net\bin\Release\netstandard1.6\ChatExchange.Net.xml
  name: ChatExchange.Net.xml
- path: '**\ChatExchange.Net*.nupkg'
  
deploy:
- provider: NuGet
  api_key:
    secure: vVmfmmg09BJVlqMuiWrSGPo0LXGlJ8HzWfysbHPpZonMQMOd82oiB+1ioKZQEsZH
  skip_symbols: true
  artifact: /.*\.nupkg/
  on:
    branch: master
