version: 6.0.{build}.0

os: Visual Studio 2017

configuration: Release

platform: Any CPU

before_build:
- dotnet restore

build:
  project: ChatExchange.Net.sln
  parallel: true
  verbosity: minimal

after_build:
- ps: msbuild /t:pack /p:Configuration=Release

artifacts:
- path: ChatExchange.Net\bin\Release\ChatExchange.Net.dll
  name: ChatExchange.Net.dll
- path: ChatExchange.Net\bin\Release\ChatExchange.Net.xml
  name: ChatExchange.Net.xml
- path: '**\ChatExchange.Net*.nupkg'
  
deploy:
- provider: NuGet
  api_key:
    secure: vVmfmmg09BJVlqMuiWrSGPo0LXGlJ8HzWfysbHPpZonMQMOd82oiB+1ioKZQEsZH
  skip_symbols: true
  artifact: /.*\.nupkg/
  on:
    branch: master
