version: 2.5.3.{build}

configuration: Release

platform: Any CPU

assembly_info:
  patch: true
  file: ChatExchange.Net\Properties\AssemblyInfo.cs
  assembly_version: '2.5.3'
  assembly_file_version: '{version}'
  assembly_informational_version: '2.5.3-beta'

before_build:
- nuget restore

build:
  project: ChatExchange.Net.sln
  parallel: true
  verbosity: minimal

after_build:
- ps: .\NuGet\pack.ps1

artifacts:
- path: ChatExchange.Net\bin\Release\ChatExchange.Net.dll
  name: ChatExchange.Net.dll
- path: '**\*.nupkg'
  
deploy:
- provider: NuGet
  api_key:
    secure: vVmfmmg09BJVlqMuiWrSGPo0LXGlJ8HzWfysbHPpZonMQMOd82oiB+1ioKZQEsZH
  skip_symbols: true
  artifact: /.*\.nupkg/
  on:
    branch: master
